### ISSUE TITLE
animate 函数报错

### ISSUE THREAD

**Issue by LIAO-wanting** [lipten/skulpt_pygame_zero#5]
你好！
我在运行测试用例animate.py的时候，发现后台显示如下报错信息：
`from pgzrun import *
alien = Actor('https://static.lipten.link/blogs/pig1.png')
alien.draw()
def on_finished():
    print("finished")
    
animate(alien, pos=(WIDTH/2, HEIGHT/2), duration=1, tween="accelerate", on_finished=on_finished)

go()`

> ExternalError: TypeError: Cannot read property 'on_finished' of undefined on line 7
看起来似乎是animate()的on_finished参数设置出现了问题😰不知道该如何解决～

**Comment by lipten** [comment]
刚试过master分支是没问题的，可以尝试在本项目运行npm run build
再用npm run server运行本项目的index.html，刚运行需要下载很多cdn资源，耐心等待一下

**Comment by LIAO-wanting** [comment]
按照您的方式运行npm run server后，终端始终报错：
`
> skulpt-pygame-zero@0.3.3 server
> node server.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'express'
`
不知是什么原因～
由于我此前有重写skulpt_pygame_zero库（添加了pygame helper）中的部分函数，因此我解决的方式是将main.js放在本地运行，将其中调用pygame-zero.js的地方修改为我更新后的代码（储存在我的github库中）：
're = {
        // "./pgzrun/__init__.js": "https://cdn.jsdelivr.net/npm/skulpt-pygame-zero@" + th.d.version + "/dist/pygame-zero.js"
        "./pgzrun/__init__.js": "https://cdn.jsdelivr.net/gh/LIAO-wanting/skulpt_pj@main/src/pgzhelper/pygame_zeroV3.js"
    }
`
运行测试用例animate.py就报错：ExternalError: TypeError: Cannot read property 'on_finished' of undefined on line 7

**Comment by lipten** [comment]
Error: Cannot find module 'express' 就是装一下express就可以了，npm run server只是静态服务启动index.html而已
然后既然你自己重写过skulpt_pygame_zero库就应该检查自己的代码中为什么ExternalError: TypeError: Cannot read property 'on_finished' of undefined on line 7

你的代码里是不是少了处理on_finished函数

**Comment by LIAO-wanting** [comment]
npm run server无法运行的问题已解决！感谢～

我之前重写过Actor类内部的函数(包括：Actor.animate() )，但这似乎对Animate类并不造成影响😥
以下部分是animate类的内部代码，貌似没有问题😭
`// 动画类
  let tweenTicker = false;
  mod.animate = Sk.misceval.buildClass(mod, function($gbl, $loc) {
    $loc.__init__ =  new Sk.builtin.func(genkwaFunc(function(args, oldkwa) {
      console.log(oldkwa)
      const kwa = Sk.ffi.remapToJs(oldkwa);
      let [self, actor, tween, duration, on_finished, targets] = args;
      tween = tween || kwa.tween || 'linear';
      duration = duration || kwa.duration || 1;
      on_finished = on_finished || oldkwa.entries.on_finished.rhs
      
      const x = transX(kwa.x) || actor.sprite.x;
      const y = transY(kwa.y) || actor.sprite.y;
      const pos = transPos(targets) || transPos(kwa.pos) || [x, y];
      return new Sk.misceval.promiseToSuspension(new Promise(function(resolve) {
        loadScript(CDN.tween, 'TWEEN').then(() => {
          if (!tweenTicker) {
            app.ticker.add(() => {
              window.TWEEN.update();
            })
            tweenTicker = true 
          }
          const {Easing} = window.TWEEN;
          const tweenMap = {
            linear: Easing.Linear.None, // 线性
            accelerate: Easing.Quartic.Out, // 加速
            decelerate: Easing.Quartic.In, // 减速
            accel_decel: Easing.Quartic.InOut, // 先加速再加速
            elastic_start: Easing.Elastic.In, // 开始时反弹
            elastic_end: Easing.Elastic.Out, // 结束时反弹
            elastic_start_end: Easing.Elastic.InOut, // 开始结束都反弹
            bounce_start: Easing.Bounce.In, // 开始时弹跳
            bounce_end: Easing.Bounce.Out, // 结束时弹跳
            bounce_start_end: Easing.Bounce.InOut, // 开始和结束都弹跳
          }
          self.ani = new window.TWEEN.Tween({
            x: actor.sprite.x,
            y: actor.sprite.y,
          }).to({
            x: pos[0] || x,
            y: pos[1] || y,
          }, duration * 1000).easing(tweenMap[tween] || Easing.Linear.None)
          .onUpdate(function (object) {
            actor.sprite.y = object.y;
            actor.sprite.x = object.x;
          }).onComplete(function() {
            on_finished && Sk.misceval.callsimOrSuspend(on_finished)
          }).start();
          resolve(void 0);
        })
    }));
    }, true))
    $loc.stop = new Sk.builtin.func(function(self) {
      self.ani.pause();
    })
    $loc.running = defineGetter(function(self) {
      return Sk.ffi.remapToPy(self.ani.tweens[0].playing);
    })
  }, 'Animate', [])
`

**Comment by lipten** [comment]
你可以在我的项目启动看没问题的话再对比一下你改的代码是否哪里有影响到的，不清楚哪块改动影响到就只能一步一步试了

**Comment by LIAO-wanting** [comment]
找到原因了～我所使用的是1.0.0版本的skulpt，其中或许缺少某种函数导致代码不能正常运行。换成最新版的skulpt后问题已解决，感谢😀
